Args = -H:+UnlockExperimentalVMOptions \
       -H:+UseServiceLoaderFeature \
       -H:ServiceLoaderFeatureExcludeServiceProviders=org.aesh.terminal.tty.provider.FfmTerminalProvider \
       -H:-UnlockExperimentalVMOptions
