Args = --initialize-at-run-time=org.aesh.terminal.tty.impl.WinSysTerminal,\
       org.aesh.terminal.tty.impl.WinSysTerminal$Handles,\
       org.aesh.terminal.tty.impl.AbstractWindowsTerminal$ConsoleOutput$OutputHandle,\
       org.aesh.terminal.tty.impl.WinConsoleNative,\
       org.aesh.terminal.tty.impl.LibC,\
       org.aesh.terminal.tty.impl.PosixConstants,\
       org.aesh.terminal.tty.impl.FfmPty,\
       org.aesh.terminal.tty.impl.FfmPty$FfmInputStream,\
       org.aesh.terminal.tty.impl.FfmPty$FfmOutputStream \
       --enable-native-access=ALL-UNNAMED \
       -H:+UnlockExperimentalVMOptions \
       -H:+SharedArenaSupport
